version: "3"

services:
  client:
    image: melihcatal/client
    ports:
      - 3000:3000
    depends_on:
      - searchservice
      - playerservice
      - compareteamservice
      - compareplayerservice
      - gameservice
  searchservice:
    image: melihcatal/searchservice

    ports:
      - 3001:3000
    depends_on:
      - mongo
  playerservice:
    image: melihcatal/playerservice

    ports:
      - 3002:3000
    depends_on:
      - mongo
  compareteamservice:
    image: melihcatal/compareteamservice

    ports:
      - 3003:3000
    depends_on:
      - mongo
  compareplayerservice:
    image: melihcatal/compareplayerservice

    ports:
      - 3004:3000
    depends_on:
      - mongo
  gameservice:
    image: melihcatal/gameservice

    ports:
      - 3005:3000
    depends_on:
      - mongo
  mongo:
    image: melihcatal/database
    ports:
      - 27017:27017
  nginx:
    image: melihcatal/nginx
    ports:
      - "8080:8080"

    depends_on:
      - client
      - playerservice
      - searchservice
      - mongo
      - compareteamservice
      - compareplayerservice
      - gameservice
