version: "3"

services:
  # client:
  #   build: 
  #     context: src/client
  #     dockerfile: ./Dockerfile
  #   image: melihcatal/client
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #   ports:
  #     - 3000:3000
  #   depends_on: 
  #     - searchservice  
  #     - playerservice
  searchservice:
    build: 
      context: src/searchService
      dockerfile: ./Dockerfile
    image: melihcatal/searchservice
    environment:
      MONGO_IP : ${MONGO_IP}
      MONGO_DATABASE : ${MONGO_DATABASE}
    ports: 
      - 3001:3000
    depends_on: 
      - mongo
  # playerservice:
  #   build: 
  #     context: src/playerService
  #     dockerfile: ./Dockerfile
  #   image: melihcatal/playerservice
  #   environment:
  #     MONGO_IP : ${MONGO_IP}
  #     MONGO_DATABASE : ${MONGO_DATABASE}
  #   ports: 
  #     - 3002:3000
  #   depends_on: 
  #     - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # - client
      # - playerservice
      - searchservice
      - mongo      
volumes:
  mongo-data:
    driver: local
