version: '3.4'

services:
  database:
    image: database
    build:
      context: src/database
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
